name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - gestione-azienda-backend/**
      
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gestione-azienda-backend
    services:
      postgres:
        image: postgres:16.1
        env:
          POSTGRES_USER: gestione-azienda
          POSTGRES_PASSWORD: gestione-azienda
          POSTGRES_DB: gestione-azienda
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify